### PR TITLE
Added onResize callback

### PR DESCRIPTION
**Pull request by kuuup-at-work**
Hi. 

I need to update some stuff while resizing. With these changes you can add a callback do `SplitterLayout`. It will be called constantly while you are dragging the splitter (so maybe debouncing is needed here).

Have fun :smiley:

### CODE REVIEW

**Comment by zesik** [comment]
Hi,

Thanks for contributing!

I tested the code and found one problem: when dragging the splitter and mouse moves out of the containing area (browser window, for instance), splitter stops responding.

In addition, I'm thinking that the `onResize` could be an optional prop and could provide some event data in callback such as current position, etc. How does this sound to you?

Could you push a fix? I'm happy to include this new feature.

**Comment by kuuup-at-work** [comment]
Hi,

I think the problem occurred because I moved `mouseup` and `mousemove` listeners to the container. It was my attempt to make this testable with `TestUtils.Simulate`. Do you have an idea how to implement a test when the listeners are bound to `document`? I'd dislike removing this test.

Providing current size or position as event data is a good idea and should be easy to implement.

**Comment by zesik** [comment]
Hi,

Any luck on this yet? After some digging, I think some extra efforts might be needed to test document events.

References:
https://github.com/facebook/react/issues/5043
https://github.com/tmpvar/jsdom/issues/1634
https://github.com/airbnb/enzyme/issues/426
http://stackoverflow.com/a/37925065

**Comment by kuuup-at-work** [comment]
Hi.

Maybe it's a good idea to rename `getSecondaryPaneSize` to `getPanelSize` and return an object containing both values. Then it would be easy to provide the primary panel size as event data for onResize.

**Comment by zesik** [comment]
Hi.

Is there any update on this?

**Comment by kuuup** [comment]
Hi. I've updated the PR a few days ago.

**Comment by zesik** [comment]
Hi,

I tested the newest commit. It seems the dragging problem is not fixed?

**Comment by kuuup-at-work** [comment]
Which browser are you using? Tried Chrome and Firefox and can't reproduce the problem.

**Comment by zesik** [comment]
Tried on Chrome. Splitter stops responding as soon as the cursor moves out of the browser window.

**Comment by kuuup-at-work** [comment]
Tested on Windows now and the splitter doesn't move when you're outside of the window but it continues when you move back in. If I move the listener back to `document` it's hard to write a test.

For me it's not a deal breaker but we can close this PR if you're unhappy with this.

**Comment by zesik** [comment]
Same behavior here. Sorry, but this is a blocker for me.

I'll leave this PR open here for now, in case you get the chance to look into this.

I posted several links a couple of days ago here, and some of them might be related to testing listeners of `document`. Hope it would be useful.

**Comment by Tsourdox** [comment]
This feature would have been amazing, any plans on fixing the issues?

**Comment by zesik** [comment]
Closing this as newest release adds this event and has better coverage test.

**Comment by kuuup-at-work** [comment]
Works! Thx!

**Pull request closed without merging**
