### PR TITLE
toggle button on splitter

### PR DESCRIPTION
**Pull request by Shawnfoto**
This is a toggle button on splitter

### CODE REVIEW

**Comment by zesik** [comment]
Thanks for contributing!

Sorry for replying late. I had several busy months. Will review soon.

**Comment by zesik** [comment]
Hi,

I like the feature! But there are several things I would like to mention:

1. Could you fix linting problems and remove unnecessary blank lines?
2. Could you rename your methods to follow others' naming convention?
3. Could you keep using some gray colors? I prefer to leave fancy color config to user customization.
4. When click to show, the splitter goes back to initial position no matter whether its position was changed before hiding. By intuition, I'd prefer it restore to previous position. Could you do that as well?

Thanks

**Comment by skrauselevy** [comment]
@zesik, since @Shawnfoto has not responded to your requested changes and this PR is relevant to what I am working on would I be able to take over so this can get merged?

**Comment by zesik** [comment]
@Shawnfoto I'd like to move forward with this feature. Could you let me know whether you are still working on this before 12 June?

**Comment by Shawnfoto** [comment]
OK, can you help me remove it

**Comment by zesik** [comment]
@Shawnfoto I see you are committing changes! Do you have plan to improve it?

If not, could you close the PR?

**Pull request closed without merging**
