### PR TITLE
Optimized mouse up listener

### PR DESCRIPTION
**Pull request by gorhawk**

### CODE REVIEW

**Comment by zesik** [comment]
Hi, why do we need this? If `resizing` is false before, there shouldn't be any re-rendering, right?

**Comment by gorhawk** [comment]
If you mean a DOM change by rendering, you are right. But the default implementation of shouldComponentUpdate just returns true. That means the lifecycle methods get called and eventually (most likely) React decides there should be no DOM change. You can help out React by not calling setState with the same state.

**Comment by gorhawk** [comment]
Yeah, found it in the docs: [https://reactjs.org/docs/react-component.html#setstate](https://reactjs.org/docs/react-component.html#setstate)

Sorry, I should've provided a description.

**Comment by zesik** [comment]
Oh, you're talking about the life cycle methods.

Will merge it. Thanks for contribution.

**Comment by gorhawk** [comment]
Yes, including render :D

**Pull request merged**
