### PR TITLE
Use the `prop-types` package as React.PropTypes is deprecated in React 15.5.0

### PR DESCRIPTION
**Pull request by torkildr**

### CODE REVIEW

**Comment by zesik** [comment]
Hi Torkild,

Thanks for contributing.

Did you get a chance to test whether this change is compatible with older React versions (0.14.0)? `prop-types` dependency is added regardless of React versions.

**Comment by torkildr** [comment]
I have not tested, but [according to the doc](https://www.npmjs.com/package/prop-types#react-014), the 0.14-branch is supported, specifically from version react 0.14.9.

I also now see that they're saying that there are some known issues prior to 15.5.7, so that should probably be the minimum version in the package.json, if using the "prop-types" package.

I'm pushing a commit with the proposed changes. Don't known what plans there are for this project, but if being strictly backwards compatible is a goal, it might make sense to do this change as a part of a major version bump

**Comment by zesik** [comment]
For minor version upgrades, I'd like to keep dependencies unchanged.
Since this PR changes some, I will merge in next major version.

**Comment by wiesson** [comment]
Any updates to this?

**Pull request merged**
